---
- hosts: all

  tasks:

    - name: Check VS_VERSION
      fail:
        msg: "VS_VERSION variable is required (e.g. vs2017 or vs2019)"
      when: "VS_VERSION is not defined"

    # Needed for WiX Toolset
    - name: Enable .NET Framework 3.5
      win_feature:
        name: "NET-Framework-Core"
        state: present

    - name: Install tools
      win_chocolatey:
        name: "{{ item }}"
        allow_empty_checksums: "yes"
      with_items:
        - kb2919355
        - kb2999226
        - kb2919442
        - 7zip.portable
        - awstools.powershell
        - cmake
        - curl
        - docfx
        - dotnet
        - dotnet-sdk
        - dotnetcore
        - git
        - jdk8
        - ninja
        - python2
        - wget
        - wixtoolset

    # Code depends on .NET Framework 4.5.2 (chocolatey package "dotnet4.5.2"),
    # but that package fails to install via Ansible due to silly limitations
    # in WinRM (see also: all the nonsense in install-kb.yml). However, the
    # framework is actually installed by default on Server 2012R2, so there's
    # no need to install it. So we just tell chocolatey to skip dependencies.
    - name: Install Visual Studio Code
      win_chocolatey:
        name: "visualstudiocode"
        ignore_dependencies: yes

    - name: Create directory structure
      win_file:
        path: C:\bin
        state: directory

    - name: Install repo
      win_copy:
        src: "repo.exe"
        dest: "C:\\bin\\repo.exe"

    - name: Add tools to PATH.
      win_path:
          elements:
          - C:\bin
          - C:\Program Files\CMake\bin
          - C:\Program Files\git\cmd
          - C:\Program Files (x86)\WiX Toolset v3.11\bin

    - name: Install OpenSSH (for Jenkins)
      script: openssh.ps1

    - name: Copy SSH config files
      win_copy:
        src: "./ssh/{{ item }}"
        dest: C:\Users\Administrator\.ssh\{{ item }}
      with_items:
        - authorized_keys
        - buildbot_id_dsa
        - config
        - environment
        - id_rsa
        - known_hosts

    - name: Copy .gitconfig file
      win_copy:
        src: "gitconfig"
        dest: C:\Users\Administrator\.gitconfig

    - name: Enable Remote Desktop
      win_regedit:
        key: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        name: fDenyTSConnections
        data: 0
        type: dword
        state: present

    - name: Open Remote Desktop in firewall
      win_firewall_rule:
        name: "remote desktop"
        enable: yes
        state: present
        localport: 3389
        action: allow
        direction: in
        protocol: TCP
        force: true

    #install role from ../roles/vs2017_mobile/
    - name: install vs2017_mobile
      include_role:
        name: "vs2017_mobile"
      vars:
        PRODUCT: "couchbase-lite-net"
      when: VS_VERSION == "vs2017"

    #install role from ../roles/vs2019_mobile/
    - name: install vs2019_mobile
      include_role:
        name: "vs2019_mobile"
      vars:
        PRODUCT: "couchbase-lite-net"
      when: VS_VERSION == "vs2019"
