version: '3.8'

# Suggested deployment command:
#   docker --host mega4.build.couchbase.com stack deploy -c athens.yaml athens
# All services, networks, etc. will then get an "athens_" prefix,
# eg. "athens_proxy"

services:
  proxy:
    deploy:
      placement:
        constraints:
          - node.labels.role==infrastructure
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_reverse-proxy"
        - "traefik.http.routers.athens.rule=Host(`goproxy.build.couchbase.com`)"
        - "traefik.http.services.athens_proxy.loadbalancer.server.port=3000"
    image: gomods/athens:v0.10.0
    init: true
    environment:
      - ATHENS_LOG_LEVEL=info
      - ATHENS_STORAGE_TYPE=disk
      - ATHENS_DISK_STORAGE_ROOT=/var/lib/athens
    volumes:
      - type: bind
        source: /buildteam/athens
        target: /var/lib/athens
    networks:
      - traefik_reverse-proxy

networks:
  traefik_reverse-proxy:
    external: true
