version: '3.8'

# Suggested deployment command:
#   docker --host mega4.build.couchbase.com stack deploy -c athens.yaml athens
# All services, networks, etc. will then get an "athens_" prefix,
# eg. "athens_proxy"

services:
  proxy:
    deploy:
      replicas: 1
    image: gomods/athens:v0.10.0
    init: true
    ports:
      - 3000:3000
    environment:
      - ATHENS_LOG_LEVEL=info
      - ATHENS_STORAGE_TYPE=disk
      - ATHENS_DISK_STORAGE_ROOT=/var/lib/athens
    volumes:
      - type: bind
        source: /buildteam/athens
        target: /var/lib/athens
    networks:
      - proxy

networks:
  proxy:
