---
- name: Install required packages for couchbase-cloud self-hosted runner VM
  block:
    - name: Add additional packages
      apt:
        name:
          - apt-transport-https
          - build-essential
          - ca-certificates
          - curl
          - docker-compose-plugin
          - gnupg
          - jq
          - lsb-release
          - parallel
          - python3-pip
          - unzip
        state: present
        update_cache: yes
      become: true
      tags: pkgs

    - name: Add Azure repo
      shell: |
        sudo mkdir -p /etc/apt/keyrings
        curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
        gpg --dearmor |
        sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=`dpkg --print-architecture` \
        signed-by=/etc/apt/keyrings/microsoft.gpg]  \
        https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
        sudo tee /etc/apt/sources.list.d/azure-cli.list

    - name: Add Azure cli
      apt:
        name:
          - azure-cli
        state: present
        update_cache: yes
      become: true
      tags: pkgs

    - name: Add gcloud repo
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] \
        https://packages.cloud.google.com/apt cloud-sdk main" |
        sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |
        sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

    - name: Add gcloud cli
      apt:
        name:
          - google-cloud-cli
        state: present
        update_cache: yes
      become: true
      tags: pkgs

    - name: Install aws cli tool
      shell:
        cmd: >
          cbdep install -d /home/couchbase/tools awscli 2.13.23 &&
          chown -R couchbase:couchbase /home/couchbase/tools &&
          ln -s /home/couchbase/tools/awscli-2.13.23/bin/aws /usr/local/bin
        creates: /usr/local/bin/aws
      become: true
      tags: pkgs

    - name: Add cleanup script
      copy:
        src: "disk_cleanup.sh"
        dest: /home/couchbase
        owner: couchbase
        group: couchbase
        mode: "0755"
      tags: diskcleanup

    - name: cron job run disk cleanup script
      cron:
        name: "Disk Cleanup"
        minute: "*/5"
        hour: "*"
        job: "/home/couchbase/disk_cleanup.sh >> /home/couchbase/disk_cleanup.log"
        state: present
      tags: diskcleanup
