version: '3.8'

# Suggested deployment command:
#  docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c server-jenkins-buildslaves.yml serverbuild
# All services, networks, etc. will then get an "serverbuild_" prefix,
# eg. "serverbuild_centos6"

# Default slave configurations. This is written using YAML anchors so
# it can be substituted into all the slave declarations later. See
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd

x-default-jenkins-secrets: &default-jenkins-secrets
  secrets:
    - source: jenkins_master_username
    - source: jenkins_master_password.20210721
      target: /run/secrets/jenkins_master_password
    - source: profiledata.ssh_privkey.profile_sync.20200423
      target: /run/secrets/profile_sync

# Use this one for an agent with one replica
x-default-jenkins-one-agent: &default-jenkins-one-agent
  deploy:
    resources:
      limits:
        memory: 9G
      reservations:
        memory: 9G
    placement:
      constraints:
        - node.labels.role==build
    replicas: 1
    update_config:
      parallelism: 1000
  networks:
    - jenkins
  <<: *default-jenkins-secrets

# Use this one for an agent with two replicas
x-default-jenkins-two-agent: &default-jenkins-two-agent
  deploy:
    resources:
      limits:
        memory: 9G
      reservations:
        memory: 9G
    placement:
      constraints:
        - node.labels.role==build
    replicas: 2
    update_config:
      parallelism: 1000
  networks:
    - jenkins
  <<: *default-jenkins-secrets

# Use this one for an agent with three replicas
x-default-jenkins-three-agent: &default-jenkins-three-agent
  deploy:
    resources:
      limits:
        memory: 9G
      reservations:
        memory: 9G
    placement:
      constraints:
        - node.labels.role==build
    replicas: 3
    update_config:
      parallelism: 1000
  networks:
    - jenkins
  <<: *default-jenkins-secrets

# Use this one for an agent with two replicas and IPv6 enabled.
# Previously only CV unit tests agents had this, so to be
# overly cautious, we'll continue only using this for CV.
x-default-jenkins-two-agent-with-ipv6: &default-jenkins-two-agent-with-ipv6
  deploy:
    resources:
      limits:
        memory: 9G
      reservations:
        memory: 9G
    placement:
      constraints:
        - node.labels.role==build
    replicas: 2
    update_config:
      parallelism: 1000
  networks:
    - jenkins
  <<: *default-jenkins-secrets
  sysctls:
    net.ipv6.conf.lo.disable_ipv6: 0

# Pointed to Jenkins master; use a YAML anchor so we can change this
# globally when necessary
x-server-jenkins-environment:
 - &server-jenkins-master "JENKINS_MASTER=http://mega1.build.couchbase.com:8082/"
x-cv-jenkins-environment:
 - &cv-jenkins-master "JENKINS_MASTER=http://cv.jenkins.couchbase.com/"

x-server-jenkins-node-class:
 - &server-jenkins-node-class "NODE_CLASS=build"
x-cv-jenkins-node-class:
 - &cv-jenkins-node-class "NODE_CLASS=cv"

# This one is still shared between server and cv
x-node-product:
 - &node-product "NODE_PRODUCT=couchbase-server"

services:
  # Placeholder service for aarch64
  # Note: this should always have zero replicas, and its image should always
  # be kept current. Its presence here is required to allow EC2 instances
  # to discover the correct image.
  amzn2_aarch64:
    image: 284614897128.dkr.ecr.us-east-2.amazonaws.com/server-amzn2-build:20220113-aarch64
    deploy:
      replicas: 0

  amzn2:
    image: couchbasebuild/server-amzn2-build:20220113-x86_64
    environment:
      - "JENKINS_SLAVE_NAME=server-amzn2"
      - "JENKINS_SLAVE_LABELS=server amzn2 alice mad-hatter cheshire-cat neo master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent

  centos6:
    image: couchbasebuild/server-centos6-build:20220117
    environment:
      - "JENKINS_SLAVE_NAME=server-centos6"
      - "JENKINS_SLAVE_LABELS=server centos6 vulcan alice mad-hatter x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
      - "JAVA_OPTS=-Djava.util.logging.config.file=/swarm-logging.properties"
    <<: *default-jenkins-one-agent

  centos7:
    image: couchbasebuild/server-centos7-build:20220111
    environment:
      - "JENKINS_SLAVE_NAME=server-centos7"
      - "JENKINS_SLAVE_LABELS=server centos7 all vulcan alice mad-hatter cheshire-cat neo master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-three-agent

  linux-single:
    image: couchbasebuild/server-linux-build:20220113
    environment:
      - "JENKINS_SLAVE_NAME=server-linux"
      - "JENKINS_SLAVE_LABELS=server linux all monster neo morpheus master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    volumes:
      - type: volume
        source: optcouchbase
        target: /opt/couchbase
      - type: volume
        source: rpmdb
        target: /var/lib/rpm
      - type: volume
        source: workspace
        target: /home/couchbase/jenkins/workspace
      - type: volume
        source: cbdepscache
        target: /home/couchbase/.cbdepscache
      - type: volume
        source: cbdepcache
        target: /home/couchbase/.cbdepcache
      - type: volume
        source: ccache
        target: /home/couchbase/.ccache
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /home/couchbase/.docker/config.json
        target: /home/couchbase/.docker/config.json
    deploy:
      resources:
        reservations:
          memory: 28GB
      placement:
        constraints:
          - node.labels.role==monster
      replicas: 2
      update_config:
        parallelism: 1000
    networks:
      - jenkins
    <<: *default-jenkins-secrets

  centos7-asan:
    image: couchbasebuild/server-centos7-build:20220111
    environment:
      - "JENKINS_SLAVE_NAME=server-centos7-asan"
      - "JENKINS_SLAVE_LABELS=server centos7-asan all cheshire-cat neo morpheus x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    deploy:
      resources:
        reservations:
          memory: 16GB
      placement:
        constraints:
          - node.labels.role==serverbuild-asan
      replicas: 1
      update_config:
        parallelism: 1000
    networks:
      - jenkins
    <<: *default-jenkins-secrets

  centos8:
    image: couchbasebuild/server-centos8-build:20210831
    environment:
      - "JENKINS_SLAVE_NAME=server-centos8"
      - "JENKINS_SLAVE_LABELS=server centos8 mad-hatter x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-three-agent

  debian8-alice:
    image: couchbasebuild/server-debian8-alice-build:20220117
    environment:
      - "JENKINS_SLAVE_NAME=server-debian8-alice"
      - "JENKINS_SLAVE_LABELS=server debian8 vulcan alice x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-one-agent

  debian8:
    image: couchbasebuild/server-debian8-build:20220117
    environment:
      - "JENKINS_SLAVE_NAME=server-debian8"
      - "JENKINS_SLAVE_LABELS=server debian8 mad-hatter cheshire-cat neo master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent

  debian9:
    image: couchbasebuild/server-debian9-build:20220114
    environment:
      - "JENKINS_SLAVE_NAME=server-debian9"
      - "JENKINS_SLAVE_LABELS=server debian9 vulcan alice mad-hatter cheshire-cat neo master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent

  debian10:
    image: couchbasebuild/server-debian10-build:20220114
    environment:
      - "JENKINS_SLAVE_NAME=server-debian10"
      - "JENKINS_SLAVE_LABELS=server debian10 mad-hatter cheshire-cat neo master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent

  rhel8-alice:
    image: build-docker.couchbase.com/couchbasebuild/server-rhel8-build:20210721
    environment:
      - "JENKINS_SLAVE_NAME=server-rhel8-alice"
      - "JENKINS_SLAVE_LABELS=server rhel8 alice x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-one-agent

  suse11:
    image: couchbasebuild/server-suse11-build:20220117
    environment:
      - "JENKINS_SLAVE_NAME=server-suse11"
      - "JENKINS_SLAVE_LABELS=server suse11 vulcan alice mad-hatter master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-one-agent

  suse12:
    image: build-docker.couchbase.com/internal/server-suse12-build:20210820
    init: true
    environment:
      - "JENKINS_SLAVE_NAME=server-suse12"
      - "JENKINS_SLAVE_LABELS=vulcan alice mad-hatter cheshire-cat neo master server suse12 suse12.2 x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent

  suse15-mad-hatter:
    image: couchbasebuild/server-suse15-mad-hatter-build:20210721
    environment:
      - "JENKINS_SLAVE_NAME=server-suse15-mad-hatter"
      - "JENKINS_SLAVE_LABELS=server suse15 mad-hatter x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent

  suse15:
    image: couchbasebuild/server-suse15-build:20220114
    environment:
      - "JENKINS_SLAVE_NAME=server-suse15"
      - "JENKINS_SLAVE_LABELS=server suse15 cheshire-cat neo master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent

  ubuntu14:
    image: couchbasebuild/server-ubuntu14-build:20220117
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu14"
      - "JENKINS_SLAVE_LABELS=server ubuntu14.04 ubuntu14 vulcan alice x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-one-agent

  ubuntu16:
    image: couchbasebuild/server-ubuntu16-build:20220114
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu16"
      - "JENKINS_SLAVE_LABELS=server ubuntu16.04 ubuntu16 vulcan alice mad-hatter x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-one-agent

  ubuntu18-mad-hatter:
    image: couchbasebuild/server-ubuntu18-mad-hatter-build:20210721
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu18-mad-hatter"
      - "JENKINS_SLAVE_LABELS=server ubuntu18.04 ubuntu18 alice mad-hatter x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-one-agent

  ubuntu18:
    image: couchbasebuild/server-ubuntu18-build:20220117
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu18"
      - "JENKINS_SLAVE_LABELS=server ubuntu18.04 ubuntu18.04-windowscrosscompile ubuntu18 cheshire-cat neo master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent

  ubuntu18-clang9:
    image: couchbasebuild/server-ubuntu18-clang9-build:20220111
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu18-clang9"
      - "JENKINS_SLAVE_LABELS=clang9 ubuntu18 ubuntu18.04 x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-one-agent

  ubuntu20-clang9:
    image: couchbasebuild/server-ubuntu20-clang9-build:20220111
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu20-clang9"
      - "JENKINS_SLAVE_LABELS=clang9 ubuntu20 ubuntu20.04 x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-one-agent

  ubuntu20:
    image: couchbasebuild/server-ubuntu20-build:20220111
    init: true
    environment:
      - "JENKINS_SLAVE_NAME=server-ubuntu20"
      - "JENKINS_SLAVE_LABELS=server ubuntu20.04 ubuntu20 mad-hatter cheshire-cat neo morpheus master x86_64"
      - *server-jenkins-master
      - *server-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent

  centos7_unittests:
    image: couchbasebuild/server-centos7-build:20220111
    environment:
      - "JENKINS_SLAVE_NAME=unit-centos7"
      - "JENKINS_SLAVE_LABELS=centos7 unit-simple-test"
      - *cv-jenkins-master
      - *cv-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent-with-ipv6

  ubuntu20_unittests:
    image: couchbasebuild/server-ubuntu20-build:20220111
    environment:
      - "JENKINS_SLAVE_NAME=unit-ubuntu20"
      - "JENKINS_SLAVE_LABELS=ubuntu20.04 ubuntu20 unit-simple-test"
      - *cv-jenkins-master
      - *cv-jenkins-node-class
      - *node-product
    <<: *default-jenkins-two-agent-with-ipv6

secrets:
  jenkins_master_username:
    external: true
  jenkins_master_password.20210721:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true

networks:
  jenkins:

volumes:
  optcouchbase:
  rpmdb:
  workspace:
  cbdepscache:
  cbdepcache:
  ccache: