version: '3.5'

# Suggested deployment command:
#  docker --host mega4.build.couchbase.com stack deploy --with-registry-auth -c cv-jenkins.yaml cv
# All services, networks, etc. will then get an "cv_" prefix,
# eg. "cv_jenkins"

services:

  # cv.jenkins.couchbase.com
  jenkins:
    image: jenkins/jenkins:2.332.2
    deploy:
      placement:
        constraints:
          - node.labels.role==infrastructure
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_reverse-proxy"
        - "traefik.http.routers.cv_jenkins.rule=Host(`cv.jenkins.couchbase.com`)"
        - "traefik.http.services.cv_jenkins.loadbalancer.server.port=8080"
    ports:
      - "50002:50002"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /buildteam/jenkins/cv-jenkins-home
        target: /var/jenkins_home
    networks:
      - jenkins
      - traefik_reverse-proxy

# See http://www.technowise.in/2016/10/fix-no-valid-crumb-was-included-in.html
# and https://wiki.jenkins-ci.org/display/JENKINS/Running+Jenkins+behind+Nginx
# for the reason behind -Dhudson.security.csrf.requestfield
    environment:
      - "JAVA_OPTS=-Dhudson.model.ParametersAction.keepUndefinedParameters=true -Dhudson.security.csrf.requestfield=Jenkins-Crumb"

networks:
  jenkins:
  traefik_reverse-proxy:
    external: true
