version: '3.8'

# Suggested deployment command:
#  docker --host 172.23.112.24 stack deploy --with-registry-auth -c cv-jenkins-agents.yml cv
# All services, networks, etc. will then get an "cv_" prefix,
# eg. "cv_ubuntu18_large"

# Default agent configuration. This is written using a YAML anchor so
# it can be substituted into all the agent declarations later. See
# https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd
x-default-jenkins-agent: &default-jenkins-agent
  networks:
    - jenkins
  sysctls:
    net.ipv6.conf.lo.disable_ipv6: 0

  secrets:
    - source: jenkins_master_username
    - source: jenkins_master_password.20210721
      target: /run/secrets/jenkins_master_password
    - source: profiledata.ssh_privkey.profile_sync.20200423
      target: /run/secrets/profile_sync
    - source: dockerhub_nsbuildbot_password
      target: /tmp/dockerhub_nsbuildbot_password

services:
  # Placeholder service for aarch64
  # Note: this should always have zero replicas, and its LAUNCH_IMAGE should
  # always be kept current. Its presence here is required to allow EC2
  # instances to discover the correct image.
  amzn2_aarch64:
    image: alpine
    environment:
      LAUNCH_IMAGE: 284614897128.dkr.ecr.us-east-2.amazonaws.com/server-amzn2-build:20210831-aarch64
    deploy:
      replicas: 0

  ubuntu18_docker:
    image: couchbasebuild/swarm-launcher:20210209

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp:/mnt"

    environment:
      LAUNCH_IMAGE: couchbasebuild/server-ubuntu18-docker-cv:20220423
      LAUNCH_PULL: "true"
      LAUNCH_EXT_NETWORKS: cv_jenkins
      LAUNCH_PRIVILEGED: "true"
      LAUNCH_ENVIRONMENTS: >-
        JENKINS_SLAVE_NAME=CV
        JENKINS_SLAVE_LABELS=docker@_@linux
        JENKINS_MASTER=http://cv.jenkins.couchbase.com/
        NODE_CLASS=cv-docker
        NODE_PRODUCT=couchbase-server
        PARALLELISM=4
      LAUNCH_VOLUMES: "/var/run/docker.sock:/var/run/docker.sock:rw"
      LAUNCH_SYSCTLS: "net.ipv6.conf.lo.disable_ipv6=0"
      LAUNCH_HOSTNAME_FROM_HOST: "true"

      LOGIN_USER: "nsbuildbot"
      LOGIN_PASSWORD_FILE: "/tmp/dockerhub_nsbuildbot_password"

    <<: *default-jenkins-agent
    deploy:
      placement:
        constraints:
          - "node.labels.cvtype==docker"
        max_replicas_per_node: 1
      replicas: 2
      update_config:
        parallelism: 100

  ubuntu18_small:
    image: couchbasebuild/swarm-launcher:20210209

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp:/mnt"

    environment:
      LAUNCH_IMAGE: couchbasebuild/server-ubuntu18-cv:20220423
      LAUNCH_PULL: "true"
      LAUNCH_EXT_NETWORKS: cv_jenkins
      LAUNCH_PRIVILEGED: "true"
      LAUNCH_ENVIRONMENTS: >-
        JENKINS_SLAVE_NAME=CV
        JENKINS_SLAVE_LABELS=u18-docker-slave@_@vulcan@_@6.5.0@_@6.5.1@_@6.5.2@_@6.6.0@_@7.0.0@_@mad-hatter@_@cheshire-cat@_@neo@_@master@_@ubuntu-18.04@_@small
        JENKINS_MASTER=http://cv.jenkins.couchbase.com/
        NODE_CLASS=cv
        NODE_PRODUCT=couchbase-server
        PARALLELISM=4
      LAUNCH_SYSCTLS: "net.ipv6.conf.lo.disable_ipv6=0"
      LAUNCH_HOSTNAME_FROM_HOST: "true"

      LOGIN_USER: "nsbuildbot"
      LOGIN_PASSWORD_FILE: "/tmp/dockerhub_nsbuildbot_password"

    <<: *default-jenkins-agent
    deploy:
      placement:
        constraints:
          - "node.labels.cvtype==ubuntu18-small"
        max_replicas_per_node: 1
      replicas: 10
      update_config:
        parallelism: 100

  ubuntu18_large:
    image: couchbasebuild/swarm-launcher:20210209

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp:/mnt"

    environment:
      LAUNCH_IMAGE: couchbasebuild/server-ubuntu18-cv:20220423
      LAUNCH_PULL: "true"
      LAUNCH_EXT_NETWORKS: cv_jenkins
      LAUNCH_PRIVILEGED: "true"
      LAUNCH_ENVIRONMENTS: >-
        JENKINS_SLAVE_NAME=CV
        JENKINS_SLAVE_LABELS=u18-docker-slave@_@vulcan@_@6.5.0@_@6.5.1@_@6.5.2@_@6.6.0@_@7.0.0@_@mad-hatter@_@cheshire-cat@_@neo@_@master@_@ubuntu-18.04@_@large
        JENKINS_MASTER=http://cv.jenkins.couchbase.com/
        NODE_CLASS=cv
        NODE_PRODUCT=couchbase-server
        PARALLELISM=16
      LAUNCH_SYSCTLS: "net.ipv6.conf.lo.disable_ipv6=0"
      LAUNCH_HOSTNAME_FROM_HOST: "true"

      LOGIN_USER: "nsbuildbot"
      LOGIN_PASSWORD_FILE: "/tmp/dockerhub_nsbuildbot_password"

    <<: *default-jenkins-agent
    deploy:
      placement:
        constraints:
          - "node.labels.cvtype==ubuntu18-large"
        max_replicas_per_node: 1
      replicas: 10
      update_config:
        parallelism: 1000

secrets:
  jenkins_master_username:
    external: true
  jenkins_master_password.20210721:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true
  dockerhub_nsbuildbot_password:
    external: true

networks:
  jenkins:
    attachable: true
