# This playbook addresses an issue affecting tsan on ubuntu 24
# https://stackoverflow.com/questions/77850769/fatal-threadsanitizer-unexpected-memory-mapping-when-running-on-linux-kernels
---
- name: Ensure sysctl config file exists
  file:
    path: /etc/sysctl.d/99-mmap_rnd_bits.conf
    state: touch
  become: true

- name: Ensure sysctl setting for vm.mmap_rnd_bits is present
  lineinfile:
    path: /etc/sysctl.d/99-mmap_rnd_bits.conf
    regexp: '^vm/mmap_rnd_bits'
    line: 'vm.mmap_rnd_bits = 28'
    state: present
  become: true

- name: Apply settings
  command: sysctl -p /etc/sysctl.d/99-mmap_rnd_bits.conf
  args:
    warn: false
  become: true
