version: '3.5'

# Suggested deployment command:
#   docker --host mega4-swarm.build.couchbase.com stack deploy -c docker-registry.yaml docker
# All services, networks, etc. will then get an "docker_" prefix,
# eg. "docker_registry"

services:
  registry:
    deploy:
      replicas: 1
    image: registry:2
    ports:
      - 443:443
    secrets:
      - source: buildhub.crt
      - source: buildhub.key
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /run/secrets/buildhub.crt
      REGISTRY_HTTP_TLS_KEY: /run/secrets/buildhub.key
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
    volumes:
      - type: bind
        source: /builds/docker/registry
        target: /var/lib/registry

secrets:
  buildhub.crt:
    external: true
  buildhub.key:
    external: true
