---
azul_jdk_name: "{{ 'zulu11.48.21-ca-jdk11.0.11-macosx_aarch64' if ansible_architecture == 'arm64' else 'zulu11.48.21-ca-jdk11.0.11-macosx_x64' }}"
homebrew_dir: "{{ '/usr/local' if ansible_architecture == 'x86_64' else '/opt/homebrew' }}"
