---
# https://docs.microsoft.com/en-us/visualstudio/install/use-command-line-parameters-to-install-visual-studio
- name: Download vs_professional.exe installer
  win_get_url:
    url: "https://aka.ms/vs/15/release/vs_professional.exe"
    dest: C:\bin\vs_professional.exe

- name: Check if MSVC2017 install
  win_stat:
    path: 'C:\Program Files (x86)\Microsoft VisualStudio\Installer\resources\app\layout\InstallCleanup.exe'
  register: msvc2017_installcleanup

- name: "Run MSVC2017 install cleanup"
  win_command: '"C:\Program Files (x86)\Microsoft VisualStudio\Installer\resources\app\layout\InstallCleanup.exe" -full'
  when: msvc2017_installcleanup.stat.exists == True

- name: Install Visual Studio Professional 2017
  win_command: C:\bin\vs_professional.exe --add Microsoft.VisualStudio.Workload.NativeDesktop --add Microsoft.VisualStudio.Workload.Universal --add Microsoft.VisualStudio.Component.VC.140 --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --includeRecommended --quiet --productKey "{{ vskey }}" --addProductLang en-US --norestart --wait --nocache
  register: install_output
  failed_when: ( install_output.rc not in [ 3010, 0 ] )

- debug: var=install_output.stdout_lines

- name: Reboot Windows
  win_reboot:
