---
- name: Install Xcode
  block:
  - name: Check XCODE_VERSION variable
    fail:
      msg: "Variable XCODE_VERSION is required (e.g. 10.3)"
    when: "XCODE_VERSION is not defined"

  - name: Copy Command Line Tools Installation Script
    copy:
      src: files/install_command_line_tools.sh
      dest: /tmp/install_command_line_tools.sh
      mode: 0755

    #Command Line Tools are likely installed by homebrew already
    #Leave this task here just in case.
  - name: Install Commmand Line Tools
    shell: /tmp/install_command_line_tools.sh
    become: true

    # Install XCode from dmg
  - name: Install Xcode Xip
    shell: |
      if [ `xcodebuild -version | grep {{ XCODE_VERSION }}`  ]; then
        echo "INFO: XCode {{ XCODE_VERSION }} is already installed!"
      else
        echo "INFO: XCode.app not found. Installing XCode..."
        curl -L -O "http://downloads.build.couchbase.com/xcode/Xcode_{{ XCODE_VERSION }}.xip"
        xip -x "Xcode_{{ XCODE_VERSION }}.xip"
        #remove old Xcode in case if there is one.
        [ -d /Applications/Xcode.app ] && rm -rf /Applications/Xcode.app
        mv Xcode.app /Applications/.
        rm -f "Xcode_{{ XCODE_VERSION }}.xip"
      fi
    become: true

  - name: Install headers (xcode)
    shell: installer -pkg /Applications/Xcode.app/Contents/Resources/Packages/XcodeSystemResources.pkg -target /
    become: true

  - name: Reset to default CLI tools path (xcode)
    shell: xcode-select -r
    become: true

  - name: Accept license (xcode)
    shell: xcodebuild -license accept
    become: true
  tags: xcode
