---
- name: Install CircleCI self-hosted launcher
  block:
    - name: Ensure ~/.ssh exists
      file:
        path: /home/couchbase/.ssh
        state: directory
        mode: "0700"
        owner: couchbase
        group: couchbase
      tags: ssh

    - name: Create couchbase-cloud .ssh config
      copy:
        src: ".ssh/{{ item }}"
        dest: /home/couchbase/.ssh
        owner: couchbase
        group: couchbase
        directory_mode: "0700"
        mode: "0600"
      loop: [ id_rsa, id_rsa.pub, known_hosts ]
      tags: ssh

    - name: Create /opt/circleci
      file:
        path: /opt/circleci
        state: directory
        mode: "0755"
        owner: couchbase
        group: couchbase
      become: true

    - name: Install CircleCI Launch Agent
      script:
        chdir: /tmp
        cmd: files/download-launch-agent.sh
        creates: /opt/circleci/circleci-launch-agent
      become: true

    - name: Add launch-agent-config
      template:
        src: launch-agent-config.yaml.j2
        dest: /opt/circleci/launch-agent-config.yaml
        owner: root
        mode: "0600"
      become: true

    - name: Add circleci systemd service file
      copy:
        src: circleci.service
        dest: /etc/systemd/system/circleci.service
        owner: root
        mode: "0644"
      become: true

    - name: Enable and Start circleci systemd service
      systemd:
        name: circleci
        enabled: true
      become: true

    - name: Add additional packages
      apt:
        name:
          - apt-transport-https
          - build-essential
          - ca-certificates
          - curl
          - docker-compose-plugin
          - gnupg
          - jq
          - lsb-release
          - python3-pip
          - unzip
        state: present
        update_cache: yes
      become: true
      tags: pkgs

    - name: Add Azure repo
      shell: |
        sudo mkdir -p /etc/apt/keyrings
        curl -sLS https://packages.microsoft.com/keys/microsoft.asc |
        gpg --dearmor |
        sudo tee /etc/apt/keyrings/microsoft.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/microsoft.gpg
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=`dpkg --print-architecture` \
        signed-by=/etc/apt/keyrings/microsoft.gpg]  \
        https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
        sudo tee /etc/apt/sources.list.d/azure-cli.list

    - name: Add Azure cli
      apt:
        name:
          - azure-cli
        state: present
        update_cache: yes
      become: true
      tags: pkgs

    - name: Add gcloud repo
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] \
        https://packages.cloud.google.com/apt cloud-sdk main" |
        sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |
        sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

    - name: Add gcloud cli
      apt:
        name:
          - google-cloud-cli
        state: present
        update_cache: yes
      become: true
      tags: pkgs

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      become: true
      tags: pkgs

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists
      become: true
      tags: pkgs

    - name: Start circleci systemd service
      systemd:
        name: circleci
        state: started
      become: true
