version: "3.8"

# Stack for general-purpose agent capable of running "docker buildx build".
#
# Note: Post-deployment, log in as admin and add Repository Observer
# permissions to the guest account for the internal and snapshot repos

services:
  buildx:
    # Historically, this was the agent used for
    # couchbase-k8s-microservice builds, so for the moment it's still
    # using the "ubuntu-2004-operator-build" image, has
    # operator-specific Jenkins labels, and runs on Swarm nodes with the
    # role "operator". In future we may further divide this.
    image: couchbasebuild/ubuntu-2004-operator-build:20220706
    user: couchbase
    environment:
      - "JENKINS_SLAVE_NAME=buildx"
      - "JENKINS_SLAVE_LABELS=couchbase-k8s-microservices couchbase-operator master buildx"
      - "JENKINS_MASTER=http://server.jenkins.couchbase.com/"
      - "NODE_CLASS=build"
      - "NODE_PRODUCT=couchbase-server"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    configs:
      - source: jenkins_master_username
        target: /run/secrets/jenkins_master_username
        mode: 0444
    secrets:
      - source: server_jenkins_ns-buildbot_api_key.20220510
        target: /run/secrets/jenkins_master_password
      - source: profiledata.ssh_privkey.profile_sync.20200423
        target: /run/secrets/profile_sync
      - source: buildx.config.docker.20220621
        target: /home/couchbase/.docker/config.json
        mode: 0600
        uid: "1000"
        gid: "1000"
    deploy:
      placement:
        constraints:
          - node.labels.role==operator
      replicas: 2
      update_config:
        parallelism: 1000

configs:
  jenkins_master_username:
    file: config/jenkins_master_username

secrets:
  server_jenkins_ns-buildbot_api_key.20220510:
    external: true
  buildx.config.docker.20220621:
    external: true
  profiledata.ssh_privkey.profile_sync.20200423:
    external: true
