---
- hosts: all
  tasks:
  - name: Check NODE_CLASS variable
    fail:
      msg: "Variable NODE_CLASS is required (e.g. build)"
    when: "NODE_CLASS is not defined"

  - name: Check SSH_KEY variable
    fail:
      msg: "Variable SSH_KEY (profile sync private key) is required"
    when: "SSH_KEY is not defined"

- hosts: all
  vars:
    homebrew_dir: "{{ '/usr/local' if ansible_architecture == 'x86_64' else '/opt/homebrew' }}"
  roles:
    - { role: 'roles/testrunner', tags: 'testrunner' }
    - { role: '../common/roles/profile', tags: 'profile' }
    - { role: 'roles/cv', tags: 'cv' }
