---
- hosts: all
  user: jenkins

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - name: Check if /usr/bin/java is already installed
      stat:
        path: /usr/bin/java
      register: java_state

    - name: Install java
      homebrew_cask: name=java state=present
      when: not java_state.stat.exists

    - name: set energy saving to zero
      shell: systemsetup -setcomputersleep Never
      become: true

    - name: Copy SSH config files
      copy:
        src=./ssh/{{ item }} dest=/Users/jenkins/.ssh/{{ item }} owner=jenkins group=staff mode=0644
      with_items:
        - authorized_keys

    - name: Add Jenkins' profile
      copy:
        src=./files/jenkins_profile dest=/Users/jenkins/.profile owner=jenkins group=staff mode=0644

    - name: Create required /opt/couchbase directory
      file: path=/opt/couchbase state=directory owner=jenkins group=staff mode=0755
      become: true

    - name: Install python 3.6
      homebrew:
        name: https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb
      tags: python3
