version: '3.8'

# Suggested deployment command:
#   docker --host mega4.build.couchbase.com stack deploy -c traefik.yaml traefik
# All services, networks, etc. will then get an "traefik_" prefix,
# eg. "traefik_traefik"

services:
  traefik:
    image: traefik:v2.3.7
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.swarmmode=true"
      - "--providers.docker.watch=true"
      - "--entrypoints.web.address=:80"
    init: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
    deploy:
      replicas: 3
      placement:
        constraints:
          - "node.role==manager"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    driver: overlay
    attachable: true
