
---
- name: Get current machine PATH.
  raw: $ENV:PATH
  register: path_out
  changed_when: false

- name: "Add {{ item }} to PATH."
  raw: SETX /M PATH "$ENV:PATH;{{ item }}"
  when: "not (path_out.stdout | urlencode | search( item | urlencode ) )"
  changed_when: true
