# sample playbook for testing and manual runs
---
- hosts: all
  gather_facts: True

  tasks:
    - include_role:
        name: "{{ rolename }}"
      loop: [ cbdep ]
      loop_control:
        loop_var: rolename
