version: '3.8'

# Suggested deployment command:
#   docker --host mega4.build.couchbase.com stack deploy -c nexus-cache.yaml nexus
# All services, networks, etc. will then get an "nexus_" prefix,
# eg. "nexus_cache"

services:
  cache:
    deploy:
      placement:
        constraints:
          - "node.labels.role==infrastructure"
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_reverse-proxy"
        - "traefik.http.routers.nexus_cache.rule=Host(`maven-cache.build.couchbase.com`)"
        - "traefik.http.services.nexus_cache.loadbalancer.server.port=8081"
    image: sonatype/nexus3
    init: true
    volumes:
      - type: bind
        source: /buildteam/nexus-cache
        target: /nexus-data
    networks:
      - traefik_reverse-proxy

networks:
  traefik_reverse-proxy:
    external: true
